forum_background:
  default: "#{$forum-background}"
  description:
    en: If you wish to change the default background add the url of the new background above.

pillar_logo:
  default: "#{$pillarlogo-medium}"
  description:
    en: If you wish to change the footer logo add the url of the new logo above.
